### ISSUE TITLE
No Good Issues To Raise

### ISSUE THREAD

**Issue by Joshua-Gordon** [SupremeSteak1/BubbleAnalytics#1]
This is literally unusable! How am I ever to use a piece of software if I can't complain about it!?

**Comment by SupremeSteak1** [comment]
I have deemed this issue unimportant and as such you will be ignored. Thank you for your help and I hope you will report any future issues!

**Comment by Joshua-Gordon** [comment]
Now there's an issue.


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Thomas Hayden <notifications@github.com> Date: 12/4/16  8:04 PM  (GMT-05:00) To: SupremeSteak1/BubbleAnalytics <BubbleAnalytics@noreply.github.com> Cc: Josh Gordon <joshua.sam.gordon@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SupremeSteak1/BubbleAnalytics] No Good Issues To Raise (#1) 
I have deemed this issue unimportant and as such you will be ignored. Thank you for your help and I hope you will report any future issues!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SupremeSteak1/BubbleAnalytics","title":"SupremeSteak1/BubbleAnalytics","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SupremeSteak1/BubbleAnalytics"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SupremeSteak1 in #1: I have deemed this issue unimportant and as such you will be ignored. Thank you for your help and I hope you will report any future issues!"}],"action":{"name":"View Issue","url":"https://github.com/SupremeSteak1/BubbleAnalytics/issues/1#issuecomment-264746828"}}}
